### ISSUE TITLE
gptool.fil is not updating header field "Datataking Machine" 

### ISSUE THREAD

**Issue by tprabu2000** [abhisrkckl/pinta#10]
**Not sure if it is an issue a pinta issue or a gptool issue**

**bash-4.2$**  header J1939+2134_59008.84702MJD_1460.000MHz_158464MiB.gptool.fil
_shows_ 
Datataking Machine               : ????

**It is fine for rficlean.fil**
**bash-4.2$**  header J1939+2134_59008.84702MJD_1460.000MHz_158464MiB.rfiClean.fil
Datataking Machine               : GMRTGSB

**checked with another set as well**
**bash-4.2$** header J1857+0943_58355.604139_1460.gptool.fil | grep Datataking
Datataking Machine               : ????
**bash-4.2$** header J1857+0943_58355.604139_1460.rfiClean.fil | grep Datataking
Datataking Machine               : GMRTGSB
**bash-4.2$**

**Thanks for looking at this issue.**

**Comment by abhisrkckl** [comment]
Shouldn't this be GMRTGWB in both cases?

**Comment by tprabu2000** [comment]
Yes, it should be GMRTGWB in both cases.  Sorry, I missed that point.

**Comment by ymaan4** [comment]
There is a fixed set of backend names/IDs in SIGPROC, and there is none
particularly for GMRTGWB or such. Because the set of IDs might even change
slightly from SIGPROC's one version to the other, you might even see
slightly different results if you use the header command from a different
version of sigproc.

As far as I know, the data taking machine (or backend name) does not have
any implications** in the rest of the processing. So, if that is the only
difference between the filterbank files produced by two branches, then I
wouldn't worry about it.

** There was one subtle implication: dspsr does not work with some
particular machine-ID/backend-names. We figured it out more than a year ago
and then BCJ changed it to "unknown" in the filterbank code that is used
right after gptool; rfiClean was already doing fine on that front.

**Comment by tprabu2000** [comment]
For completeness, I confirmed that the backend instrument names from the _*.fil_ files go as it is to the _*.fits_ files as seen below. 

**bash-4.2$** psredit J1857+0943_58355.604139_1460.gptool.fits | grep "be:name"
be:name          Name of the backend instrument            ?????

**bash-4.2$** psredit J1857+0943_58355.604139_1460.rfiClean.fits | grep "be:name"
be:name          Name of the backend instrument            GMRTFB

Although,  it will be useful if the backend instrument names are preserved in the _*.fits_ files for any future reference, fixing it through filterbank and/or dspsr codes seems outside the present plans.  We may flag this issue for a future revisit.

**Comment by abhisrkckl** [comment]
I agree. We can address this issue for a later release as it does not seem to affect the present analysis.

**Comment by abhisrkckl** [comment]
@ymaan4 @tprabu2000 
The 'be:name' property of the RFIClean FITS file is set as "GMRTFB". Should I just add this property to the gptool FITS file using psredit?

Or we can set both to GWB using psredit.

**Comment by abhisrkckl** [comment]
Decided to set 'be:name' to GWB using psredit in the Timer files.

**Comment by abhisrkckl** [comment]
Implemented in 8b296a86a2ff22d8038a9c6de3daca8567637933

**Comment by abhisrkckl** [comment]
Tested and it works.
