### ISSUE TITLE
Conversion of ascii file to fits format

### ISSUE THREAD

**Issue by praana** [abhisrkckl/pinta#27]
Hi,
I am Pranav LImaye, a bachelors project currently doing a project under Prof Yashwant Gupta at NCRA. I have taken some data from the GMRT and analysed it using gptool. I now need to convert the .gpt files from gptool into .psrfits file to verify the pulse profile shape I am getting by using psrchive. How can I proceed with this conversion?

Clear Skies,
Pranav

**Comment by abhisrkckl** [comment]
pinta runs gptool as part of its processing. You can pass the gptool.in file you created to pinta and pinta will create a Timer archive. The timer archive can be directly used for further processing. If you really want a psrfits file, you can convert the pinta output using pam or psrconv command.

Have you installed pinta? If you have, you can find detailed usage instructions in this user guide:
https://docs.google.com/document/d/13-ZWHLpGfalQ6ogbs1YSyMZjSy9gi6aFOvyQ8YYzEz8/edit?usp=sharing

**Comment by praana** [comment]
Hi,
I dont have pinta installed on my system but I can access the tapti server
of gmrt.
I will have to ask my guide to get permissions for sourcing the pinta
package.

When I analyse data using gptool I get the output pulse profile file as
"profile_filtered.gpt".
What is the extension of the timer archive file that pinta produces?

For running gptool, I source /Data/astrosoft/astrosoft.sh and this works. I
already have the .gpt files ready with me.
Can I use pinta commands on them directly to convert them into timer
archive files?

I tried converting the .gpt files into fits format using an online python
package called "YOUR'. However, when I run psredit on this fits file
I have created, the nsubint parameter is zero which effectively tells me
that the pulse profile is not phase folded. Can I workout some way out of
this error?

Clear Skies,
Pranav

**Comment by abhisrkckl** [comment]
The profile archive produced by pinta has the extension of "fits". 

To convert the gptool filtered file directly to archive, do the following.

- Make sure that the filtered gpt file and the timestamp file are in the same directory. Let us call this directory <input_dir>
- Make a new directory (Let us call this <work_dir>)
- Create a pipeline.in file inside <workdir> following the instructions given in the user guide. In the pipeline.in file, put the name of the gpt file instead of the raw data file.
- Run pinta as follows
$ pinta --no-rficlean --no-gptool <input_dir> <work_dir>

**Comment by abhisrkckl** [comment]
Note that by filtered gpt file I don't mean the ASCII profile you mentioned.  I mean the filtered data file with the name <rawdatafile>.gpt

**Comment by abhisrkckl** [comment]
@praana Is your problem resolved? If yes, I will close this issue.
